### ISSUE TITLE
Comment shortcut for Project.meta inserts // instead of #

### ISSUE THREAD

**Issue by ihowson** [esrlabs/bake-vscode-extension#6]
Repro steps:
- Open a Project.meta with Bake syntax
- Press Cmd-/ to comment a line
- Observe that `// ` is inserted at the start of the line. I expected that `# ` would be inserted.

**Comment by tfrimor** [comment]
Thanks for reporting it. I noticed it yesterday evening as well. It has been fixed in master with change 555cad7b596389a6983858676a75684fb7fe06e0
