### ISSUE TITLE
Bake 2.46 syntax support

### ISSUE THREAD

**Issue by tfrimor** [esrlabs/bake-vscode-extension#8]
- Added: Makefile command has new attribute *noClean*. If set to true, the target *clean* will not be executed when project is cleaned. Default: false.
- Added: Makefile command has new attribute *changeWorkingDir*. If set to false, bake stays in project's directory instead of changing into makefile's directory. Default: true.
- Added: Before executing the makefile, bake sets the environment variables $(BAKE_XX_COMMAND) and $(BAKE_XX_FLAGS), whereas XX is one of CPP, C, ASM, AR or LD.

**Comment by mdanilov** [comment]
Bake 2.56 syntax is supported now
